version: '3.8'
services:
  client:
    image: 'node:16'
    working_dir: /var/www
    entrypoint: yarn start
    restart: unless-stopped
    ports:
      - "80:3000"
    volumes:
      - ./client:/var/www
      - ./client/logs:/var/logs

  server:
    image: 'node:16'
    working_dir: /var/www
    entrypoint: yarn
    command: start:dev
    restart: unless-stopped
    ports:
      - "3000:3000"
      - "9229:9229"
    volumes:
      - ./server:/var/www
      - ./server/logs:/var/logs
    depends_on:
      - database

  database:
    image: 'mysql:5.7'
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    restart: unless-stopped
    ports:
      - "18765:3306"
    environment:
      MYSQL_DATABASE: dnd
      MYSQL_USER: dnd
      MYSQL_PASSWORD: dnd
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - mysql:/var/lib/mysql:delegated

volumes:
  # So that sites aren't wiped every time containers are restarted, MySQL uses a persistent volume.
  mysql: { }
